# Generated by Django 4.2.18 on 2025-02-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(blank=True, null=True, upload_to="products")),
                ("nom", models.CharField(max_length=128)),
                ("categorie", models.CharField(max_length=128)),
                ("prix", models.FloatField(verbose_name=0.0)),
                ("stock", models.IntegerField(verbose_name=0)),
            ],
        ),
    ]
