# Generated by Django 4.2.18 on 2025-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easygestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="produit",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
