# Generated by Django 4.2.18 on 2025-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easygestion", "0002_alter_produit_prix_alter_produit_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="slug",
            field=models.SlugField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
